"""Regenerate MCU metadata from the reviewed Python source maps; no device access."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))
from services.modbus.devices.mpr53cs import REGISTERS as MPR
from services.modbus.devices.tvoc2 import REGISTERS as TVOC


def render():
    lines = ['// Generated by tools/generate_register_maps.py; source metadata only.',
             '// All addresses are PDU zero-based. No write/setpoint/reset entries.',
             '#pragma once', '#include "gridsentinel/core.hpp"', 'namespace gridsentinel {']
    for label, registers in [('Mpr', MPR), ('Tvoc', TVOC)]:
        lines.append(f'inline constexpr RegisterSpec k{label}Registers[] = {{')
        for spec in registers.values():
            lines.append(f'    {{"{spec.name}", {spec.address}, {spec.width}, {float(spec.scale):g}, {str(spec.signed).lower()}, {spec.page}}},')
        lines.append('};')
    lines += ['inline constexpr ReadRange kMprFastRead{0, 86};',
              'inline constexpr ReadRange kTvocFirmwareRead{800, 2};',
              'inline constexpr ReadRange kTvocStateRead{1300, 7};',
              'inline constexpr ReadRange kTvocTripRead{100, 6};',
              'inline constexpr ReadRange kTvocDiagnosticsRead{200, 13};',
              'inline constexpr ReadRange kTvocModulesRead{500, 1};',
              'inline constexpr ReadRange kTvocSensorsRead{222, 4};',
              '} // namespace gridsentinel', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    path = ROOT / 'edge/firmware/include/gridsentinel/register_maps.hpp'
    if '--check' in sys.argv:
        if not path.exists() or path.read_text(encoding='utf-8') != render():
            raise SystemExit('Firmware register map differs from Python source; regenerate and review')
        print('Firmware and Python source maps agree')
    else:
        path.write_text(render(), encoding='utf-8')
